using TradingStuff.ResearchContracts;

namespace TradingStuff.ResearchService.Sessions;

/// <summary>
/// The platform's session authority: the only type permitted to convert between UTC and an
/// exchange-local timezone, per the doctrine on <see cref="ISessionClock"/>.
/// </summary>
/// <remarks>
/// <para>
/// Backed by <see cref="SessionGenerator"/> — the same pure function that fills
/// <c>research.sessions</c> — rather than by reads of that table. That is deliberate: if the clock
/// read the table, a stale row (generated by an older <see cref="SessionGenerator.GeneratorVersion"/>
/// and not yet re-synced) would silently disagree with freshly generated sessions, and the two
/// consumers of session boundaries — C# code through this clock, and SQL joins against the table —
/// would compute different trading dates for the same instant. Generating in both places makes that
/// disagreement impossible; <see cref="SessionCalendarService"/> exists to make the table catch up,
/// not to be the source of truth.
/// </para>
/// <para>
/// Generation is memoised per calendar-year, so lookups are in-memory after the first touch and this
/// type is safe to resolve as a singleton.
/// </para>
/// </remarks>
public sealed class SessionClock(SessionGenerator generator) : ISessionClock
{
    private const string RegularTradingHours = "RTH";

    // How far forward TradingDateOf looks for the next session before giving up. The first horizon
    // covers a normal weekend, the second a long holiday weekend, the third anything pathological
    // (the four-day 9/11 closure plus its surrounding weekends is nine calendar days).
    private static readonly int[] ForwardHorizons = [4, 12, 30];

    public SessionClock() : this(new SessionGenerator())
    {
    }

    /// <summary>The version stamped on sessions this clock produces. Matches <c>research.sessions.generator_version</c>.</summary>
    public short GeneratorVersion => SessionGenerator.GeneratorVersion;

    /// <inheritdoc />
    public TradingSession? SessionAt(string calendar, DateTimeOffset instantUtc)
    {
        var instant = instantUtc.ToUniversalTime();
        var utcDate = DateOnly.FromDateTime(instant.UtcDateTime);

        // A session's trading date is at most one day either side of the UTC date of any instant it
        // contains (the widest shipped session is the ~23h Globex day); ±2 is slack, not a guess.
        TradingSession? containing = null;

        foreach (var session in generator.Generate(calendar, utcDate.AddDays(-2), utcDate.AddDays(2)))
        {
            // Half-open [open, close): an instant exactly at a close belongs to no session, so
            // adjacent sessions can never both claim the same instant.
            if (session.OpenUtc > instant || instant >= session.CloseUtc)
            {
                continue;
            }

            // CME_ES nests its RTH row inside the full Globex day recorded as GTH, so an RTH instant
            // matches both. The more specific RTH row wins; SessionsBetween still returns both.
            if (containing is null
                || (containing.Label != RegularTradingHours && session.Label == RegularTradingHours))
            {
                containing = session;
            }
        }

        return containing;
    }

    /// <inheritdoc />
    /// <remarks>
    /// <para>
    /// Two cases, and the second is the one that matters.
    /// </para>
    /// <para>
    /// <b>Inside a session</b> ⇒ that session's trading date. This is what makes an overnight
    /// observation land correctly: a CME_ES instant at 17:30 CT on a Sunday is inside the Globex day
    /// whose trading date is MONDAY, even though both its UTC date and its exchange-local date are
    /// Sunday. Cboe GTH is the same shape — 19:15 CT Sunday through 08:15 CT Monday is Monday's
    /// session. Bucketing by either calendar date, UTC or local, gets these wrong, which is precisely
    /// how a feature computed "as of Monday" would end up reading Sunday-evening data as Sunday's.
    /// </para>
    /// <para>
    /// <b>Which calendar key to ask, and the one way to get this wrong.</b> Cboe's regular and
    /// overnight sessions are separate calendar keys. <c>CBOE_INDEX_RTH</c> answers correctly for
    /// EVERY instant — an overnight tick is not inside any RTH session, so the forward rule hands it
    /// to the RTH session it precedes, which is the same trading date <c>CBOE_INDEX_GTH</c> gives.
    /// The reverse does not hold: asking <c>CBOE_INDEX_GTH</c> about a midday RTH instant returns
    /// TOMORROW, because the next GTH session to open is that evening's. So attribute trading dates
    /// with the RTH key (or with <c>CME_ES</c>, which carries both labels), and use the GTH key only
    /// to ask whether an instant is inside an overnight session. A test pins both behaviours.
    /// </para>
    /// <para>
    /// <b>Between sessions</b> ⇒ the trading date of the NEXT session to open. An instant after
    /// Monday's close is assigned to Tuesday, never back to Monday. This direction is the leak-safe
    /// one and it is not arbitrary: assigning backwards would place post-close information on a
    /// trading date whose session had already ended, so a cutoff expressed as "trading date D" would
    /// admit data that did not exist while D was trading. Assigning forwards can only ever make
    /// information available later than it really was.
    /// </para>
    /// </remarks>
    public DateOnly TradingDateOf(string calendar, DateTimeOffset instantUtc)
    {
        var definition = generator.Data.Calendar(calendar);
        var instant = instantUtc.ToUniversalTime();
        var utcDate = DateOnly.FromDateTime(instant.UtcDateTime);

        // One day of slack: the evening before the first trading date legitimately belongs to it.
        if (utcDate < definition.EffectiveFrom.AddDays(-1))
        {
            throw new ArgumentOutOfRangeException(
                nameof(instantUtc),
                instantUtc,
                $"Calendar '{calendar}' has no sessions before {definition.EffectiveFrom:yyyy-MM-dd}; " +
                "there is no trading date to assign this instant to.");
        }

        if (SessionAt(calendar, instant) is { } containing)
        {
            return containing.TradingDate;
        }

        foreach (var horizon in ForwardHorizons)
        {
            TradingSession? next = null;

            foreach (var session in generator.Generate(calendar, utcDate.AddDays(-2), utcDate.AddDays(horizon)))
            {
                if (session.OpenUtc > instant && (next is null || session.OpenUtc < next.OpenUtc))
                {
                    next = session;
                }
            }

            if (next is not null)
            {
                return next.TradingDate;
            }
        }

        throw new InvalidOperationException(
            $"Calendar '{calendar}' has no session opening within {ForwardHorizons[^1]} days after " +
            $"{instant:O}. The calendar data most likely does not reach that far forward.");
    }

    /// <inheritdoc />
    public IReadOnlyList<TradingSession> SessionsBetween(string calendar, DateOnly from, DateOnly to) =>
        generator.Generate(calendar, from, to);

    /// <summary>Whether <paramref name="date"/> is a trading date on <paramref name="calendar"/>.</summary>
    public bool IsTradingDay(string calendar, DateOnly date) => generator.IsTradingDay(calendar, date);

    /// <summary>Every calendar key this clock can answer for.</summary>
    public IReadOnlyCollection<string> Calendars => generator.Data.CalendarKeys;
}
